"publish_receipt_bridge": {
    "publish_status": publish.get("publish_status"),
    "receipt_id": publish.get("receipt_id"),
    "media_id": publish.get("media_id"),
    "permalink": publish.get("permalink"),
    "content_type": publish.get("content_type"),
    "style": publish.get("style"),
    "created_at": publish.get("created_at"),
},
"wave11_summary": wave11_summary,
